### ISSUE TITLE
Better support for UI scaling

### ISSUE THREAD

**Issue by bachig26** [oolxg/Hanami#1]
I'm currently using Hanami on my iPhone SE 1st Gen and 3rd Gen, and as you know the 1st Gen has smaller display size and the app doesn't completely support the UI Scaling at the moment. 

I'm hoping to have the UI Scaled to support different size devices with any issues.

#### Screenshot (SE 1st Gen)

![image](https://user-images.githubusercontent.com/96393348/228184259-aa0d26a7-765a-4957-b803-a9d12a7f6557.png)![image](https://user-images.githubusercontent.com/96393348/228184258-580eb5ca-f860-4221-b5e8-ae8bb2bbcc41.png)

**Comment by oolxg** [comment]
Seems to be fixed. Also fixed size of top navigation within MangaReadingView for older iPhone versions...
