### ISSUE TITLE
continues delete prompt bug

### ISSUE THREAD

**Issue by Lenaku917** [oolxg/Hanami#10]
Came across your app on reddit and I love it! Thank you sooo much!

- delete single chapter button -> cancel -> continues delete prompt, until manual restart app
- delete single chapter -> accept -> app crash, chapter not deleted

In Depth:
I clicked on the green saved icon (downloads page -> <manga chapter> right saved icon) and on the pop up I clicked cancel. But now everytime I go in it gives me the prompt to delete, it promps again everytime when I try to scroll or click on anything except the exit button. (The trash can button, top right, does not have this issue) The issue stops when I relaunch the app. And selecting delete crashes the app before I deletes the chapter. So there is no option to delete individual chapters.

Device: iPhone 15 Pro
iOS: 17.4.1
App: v 0.28

**Comment by oolxg** [comment]
thank you for clear way of error reproduction

i fixed the crash
