### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by bachig26** [oolxg/Hanami#7]
Device: iPhone SE Gen 1
App: 0.25.5(20)
iOS: 15.8

The crash report might have been sent by TestFlight already but in any case, I have also shared what exactly happened in the additional info of the crash report.

Current Behavior:
as soon as the app homepage opens, the app crashes.

**Comment by oolxg** [comment]
Hi

I know it.

Patch is already in review @ Apple.

Also I've made a new release, that is already can be downloaded via GitHub

[release](https://github.com/oolxg/Hanami/releases/latest)

**Comment by mazulo** [comment]
I've had the same issue for the quite some time, actually. Today I was finally able to get it recorded. 

iPhone 14 Pro Max 
iOS: 17.1.1
App: 0.25.6

https://github.com/oolxg/Hanami/assets/1661112/0cc6b269-0198-416e-8274-a6177b413c06

**Comment by oolxg** [comment]
@mazulo 

Thanks

Will investigate later

**Comment by mazulo** [comment]
I don't have experience with swift but today I'm going to fork the project and run it locally to see if I can find anything. I also have a few ideas for features that would be awesome to have. Let's see if I can get something

**Comment by oolxg** [comment]
@mazulo 

Can you also explain what you did before the app crashed. Like tapped on chapter or what? From recording it's hard to understand the trigger of the crash

**Comment by mazulo** [comment]
> @mazulo 
> 
> 
> 
> Can you also explain what you did before the app crashed. Like tapped on chapter or what? From recording it's hard to understand the trigger of the crash
> 
> 
> 
> I tried to download it as on record and i got no crash :/
> 
> 

@oolxg i was just scrolling the chapters and tapping the download icon. After each time I tapped the download, I was just scrolling up so that I could expand/collapse another chapter
